### ISSUE TITLE
Pico2 + Micro Python -- low power mode problem

### ISSUE THREAD

**Issue by dsssssssss9** [FireMarshmellow/Dfrobot_Voice_Prompt_Module#3]
Hi

sorry to bother you again

when i run your excellent Micro Python demo code on my Pico2 - after the 1st  time a sample is played , the device will NOT output any further audio until either ....

1) Full hardware reset

2) reset_module() command is issued

The problem seems to be with the enter_low_power_mode() command. If this is commented out or nor called the device outputs each audio track fine.

Do you think this is a Pico2 RP2350 problem - i will try to find  my pico RP2040 tomorrow & see if i get the same problem

**Comment by FireMarshmellow** [comment]
This might be because the code doesn't have a disable a low power mode function, Can you try ascending a enable low power mode function Playing sounds again After it's already been activated. I don't think this is something DFRobot actually implemented The way users would expect, If that fails I would recommend just not using the low power mode state.

**Comment by dsssssssss9** [comment]
Hi 
many thanks

having tested further i think the best way to go , for me at least, is to as you suggested NOT to enter low power mode

once in low power mode audio playback fails most of the time

issuing a reset_module command does make audio playback work but it also resets track number so next_track() etc restart at the 1st track again

thanks for the help
